backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "post"
    label: "post"
    folder: "src/pages/post"
    create: true
    editor:
     preview: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "post"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Cover", name: image, widget: image, default: "/img/default.jpeg"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
